appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gy2ndNbmetXwweabfAdo3F+rQzaoCCb7jMe9gUAk6qajoxMqpNkNzccIN70B3wz/SA15LD64MVheRp/fGufFfebKuGArk9ufjCKGUgjhjGXBTWrQMohz4jthOs6nb7/hwtV5vMC97+aDmdWaSooDYR/+18vP6cSPVcKjUHSfWNOHU/joHoiUqW/1+PDH+v3e5yDhwOdWYigJ74pcozQdbz4vFrF1p0NV635LFUClssSH8jPDyZq1PocqZroAWfuukv95w/yVLur2GrFwgqlwqqECaj7UV1oBm55B23Gf2ObCL1xg1eMPTM4rtdiO1ruatUk4CvPgLxAQbbrExmCjRPvyjF1fi368vKMjF6GxGPzvrU6Mu2+hcZmoMTQBwHIFk9ntxVZp2Z7dq/6vDig93uX97RDqMi06qOpwX5c44u5HGTMWQfvIyUU7+k98UpYSUmuTI4ZrrYeMCOZM71nwZu3cWXL92Yp4Dvu4GwN/K0WIHbH2s3aSZPFiu8RKH2X8tUaPINT+aGh444doE59lMowfB3K2XKqdIKV4Y7ssXkPFD3Sv2uCQrRfLascEYGkRA9z00D8EOm3yYUxDAUzw/XKYWS5iv4czAuD3ibL3Wgq3Eg2DBFmbD7gd0L8LW/fzSXb6m7JgxAvs3QkdILd2NMVDmXzqXc+pgr+Aq6H3T8w=}
